### ISSUE TITLE
v1.5 package includes both rc1 and release source packages

### ISSUE THREAD

**Issue by anatolyburakov** [spandruvada/intel-speed-select-utility-src-packages#1]
I've just downloaded the v1.5 package from releases page, and it looks like the source package includes both v1.5 and v1.5-rc1 source archives. I am assuming that is not intentional :)

**Comment by spandruvada** [comment]
Thanks for finding. Not intentional. Will fix by EOD.

On Wed, 2020-08-12 at 03:56 -0700, Anatoly Burakov wrote:

I've just downloaded the v1.5 package from releases page, and it looks like the source package includes both v1.5 and v1.5-rc1 source archives. I am assuming that is not intentional :)

**Comment by spandruvada** [comment]
This was tagging issue as the latest master branch was still good. Tag v1.5 was on a previous commit which had both tar files.
